### ISSUE TITLE
AssignPhoneNumberUseCaseTests  not green

### ISSUE THREAD

**Issue by giuliopulina** [maciejwalkowiak/performance-oriented-spring-data-jpa-talk#1]
Hi Maciej,

first of all, thanks a lot for the amazing talk!

Speaking about the failing test, AssignPhoneNumberUseCaseTests:

```
 @Test
    @ExpectSelect(1)
    @ExpectUpdate(1)
    @ExpectDelete(0)
    void execute() {
        useCase.execute("sender-id", new PhoneNumber("00334455", PhoneNumber.Type.HOME));
    }

// code that is being executed
Account account = accountRepository.findByIdOrThrow(accountId);
account.addPhoneNumber(phoneNumber);
accountRepository.save(account);
```
This test fails because the following queries are executed:

```
Hibernate: select a1_0.id,a1_0.first_name,a1_0.iban,a1_0.last_name from account a1_0 where a1_0.id=?
Hibernate: select pn1_0.account_id,pn1_0.number,pn1_0.type from phone_number pn1_0 where pn1_0.account_id=?
Hibernate: delete from phone_number where account_id=?
Hibernate: insert into phone_number (account_id,number,type) values (?,?,?)
Hibernate: insert into phone_number (account_id,number,type) values (?,?,?)  
```

1. Select the account by accountId (expected)
2. Access ```account.phoneNumbers```
3. As ```account.phoneNumbers``` is a List<PhoneNumber> annotated with ```@ElementCollection```, the list behaves as a bag, so it is cleared and the phone numbers are inserted again (including the new one).

In fact, I'm not sure that the test assertions are completely correct: I would not expect any update, but just one select (account) and one insert.

[My solution](https://github.com/giuliopulina/performance-oriented-spring-data-jpa-talk/commit/3c1f0436c4c342ed32f306d24e54ae211abc0649) was to 
1. make PhoneNumber an entity 
2. adding a bidirectional ```@OneToMany``` relation between Account and PhoneNumber (marked as a Set)
3. work directly on PhoneNumber (```@ManyToOne```) to add the new phoneNumber, to avoid fetching the entire Set

Does it make sense?

Thanks,
Giulio

**Comment by niravvarma** [comment]
Yup, the test is failing. I replaced _accountRepository.findByIdOrThrow(accountId);_ with _accountRepository.getReferenceById(accountId);_ and reduced the query call by 1 and I got the following

```
Hibernate: select pn1_0.account_id,pn1_0.number,pn1_0.type from phone_number pn1_0 where pn1_0.account_id=? 
Hibernate: delete from phone_number where account_id=? 
Hibernate: insert into phone_number (account_id,number,type) values (?,?,?) 
Hibernate: insert into phone_number (account_id,number,type) values (?,?,?)
```

and then error like following

`java.lang.NoSuchMethodError: 'java.lang.String org.quickperf.sql.formatter.QuickPerfSqlFormatter$QuickPerfQueryLogEntryCreator.getLogEntry(net.ttddyy.dsproxy.ExecutionInfo, java.util.List, boolean, boolean)'

	at org.quickperf.sql.formatter.QuickPerfSqlFormatter.format(QuickPerfSqlFormatter.java:42)
	at org.quickperf.sql.SqlExecution.toString(SqlExecution.java:285)
	at org.quickperf.sql.SqlExecutions.toString(SqlExecutions.java:70)
	at org.quickperf.sql.SqlExecutions.format(SqlExecutions.java:172)
	at org.quickperf.issue.PerfIssuesToFormat.format(PerfIssuesToFormat.java:28)
	at org.quickperf.reporter.ThrowableBuilder.convertPerfIssuesToString(ThrowableBuilder.java:52)
	at org.quickperf.reporter.ThrowableBuilder.buildPerfIssuesAssertionError(ThrowableBuilder.java:25)
	at org.quickperf.reporter.IssueThrower.throwIfNecessary(IssueThrower.java:43)
	at org.quickperf.reporter.QuickPerfReporter.report(QuickPerfReporter.java:45)
	at org.quickperf.junit5.QuickPerfTestExtension.processJvmOrTestIssue(QuickPerfTestExtension.java:169)
	at org.quickperf.junit5.QuickPerfTestExtension.interceptTestMethod(QuickPerfTestExtension.java:130)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)`
	
There are 2 things which I don't understand:

- Why 4 queries are fired? I expected 3, especially the last insert, why 2 times?
- Why the error? Is something wrong?
